services:
  db_hh:
    image: postgres:latest
    container_name: db_hh
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - hh_network

  app_tg:
    build:
      dockerfile: Docker_builds/TG_Docker/Dockerfile
      context: .
    container_name: app_tg
    restart: always
    env_file:
      - project_tg/.env
    depends_on:
      - db_hh
    networks:
      - hh_network

  pars_app:
    build:
      dockerfile: Docker_builds/Parsing_Docker/Dockerfile
      context: .
    container_name: parse_app
    restart: always
    env_file:
      - project_parsing/.env
    depends_on:
      - db_hh
      - redis
    networks:
      - hh_network

  fastapi_app:
    build:
      dockerfile: Docker_builds/FastAPI_Docker/Dockerfile
      context: .
    container_name: fastapi_app
    restart: always
    env_file:
      - project_fastapi/.env
    ports:
      - "8000:8000"
    depends_on:
      - db_hh
      - redis
    networks:
      - hh_network

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hh_network

networks:
  hh_network:
    driver: bridge

volumes:
  postgres_data: